spring:
  application:
    name: controller
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firestar
    username: root
    password: 数据库密码 # Replace this with your actual password
  #邮件发送配置
  mail:
    port: 465
    default-encoding: UTF-8
    host: smtp.qq.com
    protocol: smtp
    username: 邮箱
    password: 密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  redis:
    host: localhost
    port: 6379


server:
  port: 7688
  servlet:
    context-path:  # Ensure there's no typo here

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: FireStar
  expiration: 86400000 # 1天

  logging:
    level:
      org:
        springframework:
          web:
            socket: DEBUG
          messaging: DEBUG
